# compose probably has rather little real use here.
# Probably easier just to use "docker build"
# compose becomes more useful when the script becomes a persistent service rather than a single shot executable

services:
    mirrorwobbleclassifier:
        build: .
        privileged: false
        network_mode: host
        entrypoint: /app/app_ml_server.py
        container_name: mirrorwobbleclassifier
        hostname: mirrorwobbleclassifier
        restart: unless-stopped
        tty: false
        volumes:
           - type: bind
             source: /mnt/newarchive1/Dockershare/Docker_MirrorWobbleClassifier
             target: /classifier
             read_only: false
        ports:
          - 8225:8225
        env_file:
            - mirrorwobbleclassifier.env


#  docker compose build
#  docker compose up -d
#  docker compose down

